name: AutoChecked
on:
  schedule:
    - cron: "0 7 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Auto checked for banban and vpn traffic
        run: |
          python -m pip install --upgrade pip |
          pip install requests |
          python3 
