name: AutoChecked
on:
  schedule:
    - cron: "25 0 * * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Auto checked for banban and vpn traffic
        run: |
          python -m pip install --upgrade pip |
          pip install -r .github/workflows/requirements.txt -t ./ |
          python3 .github/workflows/index.py 
